name: Docker image CI

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/README.md'

jobs:
  build:
    name: Build and publish Docker image to Docker Hub and GitHub Containers Repository
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - id: lower-repo
      name: Repository to lowercase
      run: |
        echo "repository=${GITHUB_REPOSITORY@L}" >> $GITHUB_OUTPUT

    - name: Generate Github Container Registry Image Name
      uses: mad9000/actions-find-and-replace-string@3
      id: ghcrio_image_name
      with:
        source: ${{ steps.lower-repo.outputs.repository }}
        find: '_docker'
        replace: ''

    - name: Generate Docker Hub Image Name
      uses: mad9000/actions-find-and-replace-string@3
      id: dockerhub_image_name
      with:
        source: ${{ steps.ghcrio_image_name.outputs.value }}
        find: ${{ github.repository_owner }}
        replace: ${{ vars.DOCKERHUB_USERNAME }}
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push (ghcr.io)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ steps.ghcrio_image_name.outputs.value }}:latest
    - name: Build and push (hub.docker.com)
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ${{ steps.dockerhub_image_name.outputs.value }}:latest
